#!/bin/bash
set -e

langs=`mktemp -d`
echo '```c'            > "$langs/c"
echo '```c'            > "$langs/h"
echo '```cpp'          > "$langs/cc"
echo '```cpp'          > "$langs/hh"
echo '```gnuassembler' > "$langs/S"

echo "## $1"
echo
cat $langs/`echo $1 | cut -d. -f2` 2>/dev/null || echo '```'
cat "$1"
echo '```'
