name: CI

on: push

jobs:
  Build_RasPi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: ./build raspi
      - uses: actions/upload-artifact@v2
        with:
          name: kernel8.img
          path: kernel8.img
