name: CI

on: push

jobs:
  Build_RasPi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: docker/build-push-action@v2.7.0
        with:
          tags: amplos-build
          push: false
      - uses: addnab/docker-run-action@v3
        with:
          image: amplos-build
          run: make -j$(nproc) raspi
      - uses: actions/upload-artifact@v2
        with:
          name: kernel8.img
          path: kernel8.img
